name: Build mpv (master)

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: mpv-build
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          brew update
          brew install \
            aom \
            autoconf \
            libarchive \
            automake \
            dav1d \
            fdk-aac \
            fontconfig \
            mujs \
            freetype \
            fribidi \
            glslang \
            gmp \
            gnutls \
            harfbuzz \
            jpeg-xl \
            lame \
            libarchive \
            libass \
            libbluray \
            libvmaf \
            libgme \
            libmodplug \
            libogg \
            opus \
            libplacebo \
            librsvg \
            libsoxr \
            samba \
            libssh \
            libtool \
            libvorbis \
            libvpx \
            webp \
            libxml2 \
            libzip \
            zimg \
            meson \
            molten-vk \
            ninja \
            openssl@3 \
            pkg-config \
            rav1e \
            shaderc \
            snappy \
            svt-av1 \
            vulkan-loader \
            x264 \
            x265 \
            xxhash \
            libvidstab \
            libcdio \
            libcdio-paranoia \
            libdvdnav

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
          key: cargo-${{ runner.os }}-cargo-c-v1

      - name: Install cargo-c
        run: |
          if ! cargo cinstall --help >/dev/null 2>&1; then
              cargo install cargo-c --locked
          fi
